### ISSUE TITLE
can not enable the plugin

### ISSUE THREAD

**Issue by gh16683170** [valentine195/links-in-code-block#1]
I copy all the files to the obsidian plugin window. I can not find the style.css from the source code, does it matter?
The plugin can show in obsidian menu, but when I switch on, it shows that "Failed to load links-in-code-blocks" in the up right corner.
![image](https://user-images.githubusercontent.com/16650849/112563708-d640e780-8e14-11eb-832a-0e2553607300.png)

**Comment by valentine195** [comment]
Hmm... that's odd. I just deleted and re-added the plugin a few times without issue.

Can you try with v0.0.4?

Also, yeah, no CSS file.

**Comment by gh16683170** [comment]
I try to close all the other plugins, and try with v0.04, but it showed the same error. What can I do to provide more infomation? Is there a debug mode to print some log? My os is windows10.

**Comment by gh16683170** [comment]
I opened dev mode, it shows the error that:
Plugin failure: links-in-code-blocks SyntaxError: Cannot use import statement outside a module
    at eval (<anonymous>)
    at app.js:1
    at e.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)

**Comment by gh16683170** [comment]
so sorry, i made a mistake, i directly copy the source code to the plugin folder. i use the release code, then no problem.
