### ISSUE TITLE
[enhance] custom style for links-in-code-block

### ISSUE THREAD

**Issue by gh16683170** [valentine195/links-in-code-block#6]
Last thing, if this plugin can custom the font color in the code blocks(no need syntax highlighting, just can change the default font color), it will be perfect. may be add a style.css?

**Comment by valentine195** [comment]
Would this be something applied to _all_ ’links’ code blocks?

**Comment by gh16683170** [comment]
yes. To applied to all please.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 30, 2021 07:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [valentine195/links-in-code-block] [enhance] custom style for links-in-code-block (#6)




 
Would this be something applied to all ’links’ code blocks?

**Comment by gh16683170** [comment]
wow, i didn't notice there is a `clike` feature before, that is better then i want. thanks!!

**Comment by gh16683170** [comment]
the feature can set what language we want to syntax highlighting is better then what i want.
